### ISSUE TITLE
error running evalSAD.sh

### ISSUE THREAD

**Issue by riebling** [aclew/DiViMe#4]
I can't seem to run this, even with a fresh VM.
First problem: ldc_sad_hmm was removed :)  That's covered elsewhere.
Second problem: after 'obtaining' a copy, when I run `tools/evalSAD.sh data ldc_sad` on the SAD data from the DIHARD Evaluation, this error:
```
WARNING: Problem loading segmentation from /vagrant/data/temp_ref/DH_0071..lab. Skipping.
Traceback (most recent call last):
  File "score.py", line 162, in <module>
    args.ref_lab_ext)
  File "score.py", line 117, in score_files
    ref_speech_dur, ref_nonspeech_dur, fa_dur, miss_dur = durs
ValueError: need more than 1 value to unpack
```

**Comment by riebling** [comment]
the files actually in /vagrant/data/temp_ref/ are normal names like DH_0001.lab

**Comment by riebling** [comment]
evalSAD has evolved, and I can not even reproduce this. It was mostly human error, me complaining-in-the-process-of-learning (as I tend to overdo) "why doesn't this work for me?". It's OK and should close :)
